-- MySQL Script generated by MySQL Workbench
-- Ter 20 Set 2016 19:13:36 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EspaçoAluno
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EspaçoAluno` ;

-- -----------------------------------------------------
-- Schema EspaçoAluno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EspaçoAluno` DEFAULT CHARACTER SET utf8 ;
USE `EspaçoAluno` ;

-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Student` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Student` (
  `ra` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sex` VARCHAR(45) NOT NULL,
  `civilState` VARCHAR(45) NOT NULL,
  `fatherName` VARCHAR(45) NOT NULL,
  `motherName` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `cityBirth` VARCHAR(45) NOT NULL,
  `estateBirth` VARCHAR(45) NOT NULL,
  `nacionality` VARCHAR(45) NOT NULL,
  `id` VARCHAR(45) NOT NULL,
  `address` VARCHAR(1000) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `general information` VARCHAR(45) NOT NULL,
  `currentSemester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Message` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Message` (
  `idMessage` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` VARCHAR(3000) NOT NULL,
  `Student_ra` INT NOT NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `fk_Message_Student1_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Message_Student1`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Teacher` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Teacher` (
  `ra` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `class` VARCHAR(45) NOT NULL,
  `course` VARCHAR(45) NOT NULL,
  `Student_ra` INT NOT NULL,
  PRIMARY KEY (`ra`),
  INDEX `fk_Teacher_Student_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Teacher_Student`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Declarations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Declarations` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Declarations` (
  `registrations` VARCHAR(200) NOT NULL,
  `studentPass` VARCHAR(200) NOT NULL,
  `selectionApproval` VARCHAR(200) NOT NULL,
  `Student_ra` INT NOT NULL,
  INDEX `fk_Declarations_Student1_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Declarations_Student1`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Consultations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Consultations` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Consultations` (
  `history` VARCHAR(200) NOT NULL,
  `disciplines` VARCHAR(200) NOT NULL,
  `schedule` VARCHAR(200) NOT NULL,
  `gradesNfrequenci` VARCHAR(200) NOT NULL,
  `studentPass` VARCHAR(200) NOT NULL,
  `curriculum` VARCHAR(200) NOT NULL,
  `Consultationscol` VARCHAR(200) NOT NULL,
  `complementaryActivities` VARCHAR(200) NOT NULL,
  `Student_ra` INT NOT NULL,
  INDEX `fk_Consultations_Student1_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Consultations_Student1`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Processes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Processes` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Processes` (
  `idProcesses` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `body` VARCHAR(3000) NOT NULL,
  `Student_ra` INT NOT NULL,
  PRIMARY KEY (`idProcesses`),
  INDEX `fk_Processes_Student1_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Processes_Student1`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EspaçoAluno`.`Finances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EspaçoAluno`.`Finances` ;

CREATE TABLE IF NOT EXISTS `EspaçoAluno`.`Finances` (
  `payments` VARCHAR(300) NOT NULL,
  `recipt` VARCHAR(300) NOT NULL,
  `contract` VARCHAR(300) NOT NULL,
  `paymentAntecipation` VARCHAR(300) NOT NULL,
  `Student_ra` INT NOT NULL,
  INDEX `fk_Finances_Student1_idx` (`Student_ra` ASC),
  CONSTRAINT `fk_Finances_Student1`
    FOREIGN KEY (`Student_ra`)
    REFERENCES `EspaçoAluno`.`Student` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
